//! `ChatChannel`: a chat's reply as it streams (RubyLLM's chat_ui `broadcasts_to` +
//! `broadcast_append_chunk`). Generated by `rust-llm generate chat_ui`, in the shape
//! `cargo loco generate channel` writes.
//!
//! Clients subscribe with `{account: "<slug>", id: <chat id>}` (`useChannel("ChatChannel", …)` in
//! `frontend/pages/chats/show.tsx`); members of that account are accepted when the chat is
//! theirs, and stream `"{account_id}:{chat_id}"`. The worker (`src/workers/chat_response.rs`)
//! broadcasts:
//!
//! - `{"type": "message_start", "message_id"}`: the assistant row exists (empty).
//! - `{"type": "chunk", "message_id", "content"}`: text added to it since the last chunk event.
//! - `{"type": "message_end", "message_id"}`: the row is written (content, tool calls, usage);
//!   tool results arrive as a start and an end.
//! - `{"type": "error", "message"}`: the reply failed; nothing was kept.

use loco_rs::prelude::*;
use serde::Serialize;
use serde_json::Value;

use crate::{
    auth::CurrentSession,
    live::{self, Channel, Subscription},
    models::chats,
};

pub struct ChatChannel;

impl ChatChannel {
    pub const NAME: &'static str = "ChatChannel";

    /// `ChatChannel.broadcast_to(chat, payload)`: every accepted subscription to chat `id` in
    /// account `account_id` receives `payload`.
    pub fn broadcast_to(account_id: i64, id: impl std::fmt::Display, payload: impl Serialize) {
        live::broadcast_to(Self::NAME, Self::key(account_id, id), payload);
    }

    /// The stream key: the account is part of it, so a subscription accepted in one account
    /// never receives another account's broadcast for the same id.
    fn key(account_id: i64, id: impl std::fmt::Display) -> String {
        format!("{account_id}:{id}")
    }
}

#[async_trait]
impl Channel for ChatChannel {
    fn name(&self) -> &'static str {
        Self::NAME
    }

    /// Members of the account in `params.account`, for a chat of that account.
    async fn subscribed(
        &self,
        ctx: &AppContext,
        user: &CurrentSession,
        params: &Value,
    ) -> Result<Subscription> {
        let Some(membership) = super::membership(ctx, user, params).await else {
            return live::reject();
        };
        let Some(id) = params["id"].as_i64().and_then(|id| i32::try_from(id).ok()) else {
            return live::reject();
        };
        if chats::find_in_account(&ctx.db, membership.account_id, id)
            .await?
            .is_none()
        {
            return live::reject();
        }
        Ok(Subscription::stream_for(Self::key(membership.account_id, id)))
    }
}
