//! `PublicChatController`: a chat anyone can try without signing in. Generated by
//! `rust-llm generate public_chat`.
//!
//! - **No account, no rows.** A guest's conversation is kept in this process's memory under a
//!   random, unguessable id in the HttpOnly `public_chat` cookie, which lasts for the browser
//!   session; it is forgotten after [`IDLE`] without a message, or when the guest starts over.
//! - **Streaming.** `POST /chat/messages` answers with the reply itself as Server-Sent Events
//!   (`{type: "chunk", content}` as tokens arrive, then `{type: "end", content}` or
//!   `{type: "error", message}`). Nothing is broadcast, so one guest's reply can only ever reach
//!   the request that asked for it.
//! - **Limits** ([`Limits`], from `PUBLIC_CHAT_*` environment variables): messages per client IP
//!   and per conversation within a window, input length, output tokens per reply, and turns per
//!   conversation. Over a limit the answer is a 413 or 429 with a message the page shows.
//!
//! Each reply calls the model with the app's provider key. Keep the limits tight on a public
//! deployment.

use std::{
    collections::HashMap,
    net::IpAddr,
    sync::{LazyLock, Mutex, PoisonError},
    time::{Duration, Instant},
};

use axum::{
    extract::FromRequestParts,
    http::{header, request::Parts, HeaderMap, HeaderValue, StatusCode},
    response::sse::{Event, KeepAlive, Sse},
    Json,
};
use futures_util::stream;
use loco_rs::prelude::*;
use rand::Rng;
use serde::Deserialize;
use serde_json::{json, Value};
use tokio::sync::mpsc;

use crate::{
    controllers::{render, settings, NoPrecognition, Params},
    inertia::{cookies, render::Inertia},
    route_table,
};

/// The cookie naming a guest's conversation.
pub const COOKIE: &str = "public_chat";
/// A conversation nobody has written to for this long is forgotten.
pub const IDLE: Duration = Duration::from_secs(60 * 60);
/// The most conversations kept at once; past it, the idlest go first.
pub const MAX_CONVERSATIONS: usize = 10_000;
/// What a guest sees when a rate limit is hit.
pub const SLOW_DOWN: &str = "You're sending messages faster than this demo allows. Please wait a few minutes and try again.";

/// The public chat's limits. Defaults are friendly to someone trying it out; each can be set
/// with an environment variable, and tests insert their own into `ctx.shared_store`.
#[derive(Debug, Clone)]
pub struct Limits {
    /// Messages one client IP may send per `window` (`PUBLIC_CHAT_IP_MESSAGES`, 20).
    pub ip_messages: u32,
    /// Messages one conversation may send per `window` (`PUBLIC_CHAT_SESSION_MESSAGES`, 10).
    pub session_messages: u32,
    /// The rate-limit window (`PUBLIC_CHAT_WINDOW_SECS`, 600).
    pub window: Duration,
    /// The longest message, in characters (`PUBLIC_CHAT_MAX_INPUT_CHARS`, 4,000).
    pub max_input_chars: usize,
    /// The most tokens one reply may use (`PUBLIC_CHAT_MAX_OUTPUT_TOKENS`, 1,024).
    pub max_output_tokens: i64,
    /// The most messages a guest may send in one conversation (`PUBLIC_CHAT_MAX_TURNS`, 20).
    pub max_turns: usize,
    /// The model (`PUBLIC_CHAT_MODEL`; else RustLLM's `default_model`, `RUST_LLM_DEFAULT_MODEL`).
    pub model: String,
    /// The provider, when the model id alone is ambiguous (`PUBLIC_CHAT_PROVIDER`).
    pub provider: Option<String>,
    /// The system prompt (`PUBLIC_CHAT_INSTRUCTIONS`).
    pub instructions: String,
}

impl Limits {
    #[must_use]
    pub fn from_env() -> Self {
        fn var<T: std::str::FromStr>(name: &str, default: T) -> T {
            std::env::var(name)
                .ok()
                .and_then(|v| v.trim().parse().ok())
                .unwrap_or(default)
        }
        let text = |name: &str| std::env::var(name).ok().filter(|v| !v.trim().is_empty());
        Self {
            ip_messages: var("PUBLIC_CHAT_IP_MESSAGES", 20),
            session_messages: var("PUBLIC_CHAT_SESSION_MESSAGES", 10),
            window: Duration::from_secs(var("PUBLIC_CHAT_WINDOW_SECS", 600)),
            max_input_chars: var("PUBLIC_CHAT_MAX_INPUT_CHARS", 4_000),
            max_output_tokens: var("PUBLIC_CHAT_MAX_OUTPUT_TOKENS", 1_024),
            max_turns: var("PUBLIC_CHAT_MAX_TURNS", 20),
            model: text("PUBLIC_CHAT_MODEL")
                .unwrap_or_else(|| rust_llm::config().default_model.clone()),
            provider: text("PUBLIC_CHAT_PROVIDER"),
            instructions: text("PUBLIC_CHAT_INSTRUCTIONS").unwrap_or_else(|| {
                "You are a friendly assistant in a public demo. Keep answers short.".to_owned()
            }),
        }
    }

    fn of(ctx: &AppContext) -> Self {
        ctx.shared_store.get::<Self>().unwrap_or_else(Self::from_env)
    }
}

/// A token bucket: `limit` tokens, refilled at `limit` per `window` (the kit's `RateLimiter`).
#[derive(Clone, Copy)]
struct Bucket {
    tokens: f64,
    updated: Instant,
}

impl Bucket {
    fn take(slot: &mut Option<Self>, limit: u32, window: Duration, now: Instant) -> bool {
        let limit = f64::from(limit);
        let rate = limit / window.as_secs_f64().max(f64::EPSILON);
        let bucket = slot.get_or_insert(Self {
            tokens: limit,
            updated: now,
        });
        bucket.tokens =
            (bucket.tokens + now.duration_since(bucket.updated).as_secs_f64() * rate).min(limit);
        bucket.updated = now;
        if bucket.tokens >= 1.0 {
            bucket.tokens -= 1.0;
            true
        } else {
            false
        }
    }
}

/// One guest's conversation.
struct Conversation {
    messages: Vec<rust_llm::Message>,
    turns: usize,
    /// A reply is streaming; a second message waits for it.
    busy: bool,
    rate: Option<Bucket>,
    seen: Instant,
}

#[derive(Default)]
struct Guests {
    conversations: HashMap<String, Conversation>,
    ips: HashMap<IpAddr, Option<Bucket>>,
}

/// In memory, like the kit's live hub: one process, gone on restart.
static GUESTS: LazyLock<Mutex<Guests>> = LazyLock::new(Mutex::default);

fn guests() -> std::sync::MutexGuard<'static, Guests> {
    GUESTS.lock().unwrap_or_else(PoisonError::into_inner)
}

/// Forget every conversation and rate bucket (tests start from nothing).
pub fn reset() {
    *guests() = Guests::default();
}

impl Guests {
    fn sweep(&mut self, now: Instant, window: Duration) {
        self.conversations
            .retain(|_, c| c.busy || now.duration_since(c.seen) < IDLE);
        self.ips.retain(|_, b| {
            b.is_some_and(|b| now.duration_since(b.updated) < window)
        });
        if self.conversations.len() >= MAX_CONVERSATIONS {
            let mut idle: Vec<(Instant, String)> = self
                .conversations
                .iter()
                .filter(|(_, c)| !c.busy)
                .map(|(id, c)| (c.seen, id.clone()))
                .collect();
            idle.sort();
            for (_, id) in idle.into_iter().take(MAX_CONVERSATIONS / 10) {
                self.conversations.remove(&id);
            }
        }
    }
}

/// The client's address, as the kit's rate limits see it.
pub struct ClientIp(pub IpAddr);

impl<S: Send + Sync> FromRequestParts<S> for ClientIp {
    type Rejection = std::convert::Infallible;

    async fn from_request_parts(parts: &mut Parts, _: &S) -> Result<Self, Self::Rejection> {
        // Without a known client address every guest shares one bucket.
        Ok(Self(
            crate::auth::client_ip(parts)
                .await
                .unwrap_or(IpAddr::from([0, 0, 0, 0])),
        ))
    }
}

fn conversation_id(headers: &HeaderMap) -> Option<String> {
    cookies::request_jar(headers)
        .get(COOKIE)
        .map(|c| c.value().to_owned())
        .filter(|id| id.len() == 43 && id.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_'))
}

fn new_conversation_id() -> String {
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
    let mut bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    URL_SAFE_NO_PAD.encode(bytes)
}

/// The session cookie (no expiry: gone when the browser closes) naming conversation `id`.
fn set_cookie(ctx: &AppContext, headers: &mut HeaderMap, id: &str) -> Result<()> {
    let mut cookie = cookies::base_cookie(&*settings(ctx)?, COOKIE, id.to_owned());
    cookie.set_http_only(true);
    cookies::append_set_cookie(headers, &cookie);
    Ok(())
}

fn message_props(messages: &[rust_llm::Message]) -> Vec<Value> {
    messages
        .iter()
        .filter(|m| matches!(m.role, rust_llm::Role::User | rust_llm::Role::Assistant))
        .map(|m| json!({ "role": m.role.as_str(), "content": m.content() }))
        .collect()
}

fn model_label(limits: &Limits) -> String {
    rust_llm::models()
        .find(&limits.model, limits.provider.as_deref())
        .map_or_else(|_| limits.model.clone(), |m| m.label())
}

/// `GET /chat`: the page, with this browser's conversation so far.
async fn show(State(ctx): State<AppContext>, headers: HeaderMap, inertia: Inertia) -> Result<Response> {
    let limits = Limits::of(&ctx);
    let (messages, turns) = conversation_id(&headers)
        .and_then(|id| {
            guests()
                .conversations
                .get(&id)
                .map(|c| (message_props(&c.messages), c.turns))
        })
        .unwrap_or_default();
    let props = json!({
        "messages": messages,
        "model_label": model_label(&limits),
        "limits": {
            "max_input_chars": limits.max_input_chars,
            "max_turns": limits.max_turns,
            "turns_left": limits.max_turns.saturating_sub(turns),
        },
    });
    render(inertia, "public_chat/show", props).await
}

#[derive(Debug, Deserialize)]
pub struct MessageParams {
    #[serde(default)]
    content: String,
}

fn refuse(status: StatusCode, message: &str) -> Response {
    (status, Json(json!({ "error": message }))).into_response()
}

/// `POST /chat/messages` `{content}`: the reply, streamed as Server-Sent Events.
async fn create(
    _: NoPrecognition,
    State(ctx): State<AppContext>,
    ClientIp(ip): ClientIp,
    headers: HeaderMap,
    Params(params): Params<MessageParams>,
) -> Result<Response> {
    let limits = Limits::of(&ctx);
    let content = params.content.trim().to_owned();
    if content.is_empty() {
        return Ok(refuse(StatusCode::UNPROCESSABLE_ENTITY, "Type a message first."));
    }
    if content.chars().count() > limits.max_input_chars {
        return Ok(refuse(
            StatusCode::PAYLOAD_TOO_LARGE,
            &format!(
                "That message is too long: keep it under {} characters.",
                limits.max_input_chars
            ),
        ));
    }
    let now = Instant::now();
    let existing = conversation_id(&headers);
    let id = existing.clone().unwrap_or_else(new_conversation_id);
    let history = {
        let mut guests = guests();
        guests.sweep(now, limits.window);
        let ip_ok = Bucket::take(
            guests.ips.entry(ip).or_default(),
            limits.ip_messages,
            limits.window,
            now,
        );
        let conversation = guests
            .conversations
            .entry(id.clone())
            .or_insert_with(|| Conversation {
                messages: Vec::new(),
                turns: 0,
                busy: false,
                rate: None,
                seen: now,
            });
        if conversation.busy {
            return Ok(refuse(
                StatusCode::CONFLICT,
                "Wait for the reply to finish before sending another message.",
            ));
        }
        if conversation.turns >= limits.max_turns {
            return Ok(refuse(
                StatusCode::TOO_MANY_REQUESTS,
                &format!(
                    "This conversation has reached its {} messages. Start a new one to keep going.",
                    limits.max_turns
                ),
            ));
        }
        let session_ok = Bucket::take(
            &mut conversation.rate,
            limits.session_messages,
            limits.window,
            now,
        );
        if !ip_ok || !session_ok {
            tracing::warn!(%ip, "public chat rate limited");
            return Ok(refuse(StatusCode::TOO_MANY_REQUESTS, SLOW_DOWN));
        }
        conversation.busy = true;
        conversation.seen = now;
        conversation.messages.clone()
    };

    let mut chat = match rust_llm::Chat::new(Some(&limits.model), limits.provider.as_deref()) {
        Ok(chat) => chat
            .with_instructions(limits.instructions.clone())
            .with_max_output_tokens(limits.max_output_tokens),
        Err(e) => {
            finish(&id, None);
            tracing::error!(error = %e, model = limits.model, "public chat model is not available");
            return Ok(refuse(StatusCode::SERVICE_UNAVAILABLE, "The chat is not available right now."));
        }
    };
    let instructions: Vec<rust_llm::Message> = chat.messages().to_vec();
    chat.set_messages(instructions.into_iter().chain(history).collect());

    let (tx, rx) = mpsc::unbounded_channel::<Value>();
    let conversation = id.clone();
    tokio::spawn(async move {
        let chunks = tx.clone();
        let mut streamed = String::new();
        let outcome = chat
            .ask_stream(content, |chunk| {
                let text = chunk.content();
                // Some protocols end with one more chunk holding the whole message.
                if text.is_empty() || (!streamed.is_empty() && text == streamed) {
                    return;
                }
                streamed.push_str(text);
                let _ = chunks.send(json!({ "type": "chunk", "content": text }));
            })
            .await;
        match outcome {
            Ok(reply) => {
                let messages: Vec<rust_llm::Message> = chat
                    .messages()
                    .iter()
                    .filter(|m| m.role != rust_llm::Role::System)
                    .cloned()
                    .collect();
                finish(&conversation, Some(messages));
                let _ = tx.send(json!({ "type": "end", "content": reply.content() }));
            }
            Err(e) => {
                tracing::error!(error = %e, "public chat reply failed");
                finish(&conversation, None);
                let _ = tx.send(json!({
                    "type": "error",
                    "message": "The assistant couldn't answer just now. Please try again.",
                }));
            }
        }
    });

    let events = stream::unfold(rx, |mut rx| async move {
        let frame = rx.recv().await?;
        let event = Event::default()
            .json_data(&frame)
            .unwrap_or_else(|_| Event::default().comment("unserializable"));
        Some((Ok::<_, std::convert::Infallible>(event), rx))
    });
    let mut res = Sse::new(events)
        .keep_alive(KeepAlive::new().interval(Duration::from_secs(15)))
        .into_response();
    // Proxies (nginx) must pass the reply through as it is written.
    res.headers_mut()
        .insert("x-accel-buffering", HeaderValue::from_static("no"));
    res.headers_mut()
        .insert(header::CACHE_CONTROL, HeaderValue::from_static("no-cache"));
    if existing.is_none() {
        set_cookie(&ctx, res.headers_mut(), &id)?;
    }
    Ok(res)
}

/// The reply is done: keep the conversation (`Some`, a turn spent) or leave it as it was.
fn finish(id: &str, messages: Option<Vec<rust_llm::Message>>) {
    if let Some(conversation) = guests().conversations.get_mut(id) {
        conversation.busy = false;
        conversation.seen = Instant::now();
        if let Some(messages) = messages {
            conversation.messages = messages;
            conversation.turns += 1;
        }
    }
}

/// `DELETE /chat`: start over (the old conversation is forgotten; rate limits still apply).
async fn destroy(_: NoPrecognition, headers: HeaderMap) -> Result<Response> {
    if let Some(id) = conversation_id(&headers) {
        let mut guests = guests();
        if guests.conversations.get(&id).is_some_and(|c| !c.busy) {
            guests.conversations.remove(&id);
        }
    }
    Ok(crate::inertia::redirect::Redirect::to(route_table::PUBLIC_CHAT).into_response())
}

pub fn routes() -> Routes {
    Routes::new()
        .add(route_table::PUBLIC_CHAT, get(show).delete(destroy))
        .add(route_table::PUBLIC_CHAT_MESSAGES, post(create))
}
