//! `{{class_name}}`, a RustLLM agent (RubyLLM's `agent.rb.tt`). Generated by
//! `rust-llm generate agent`. Declare `model`, `tools`, `temperature`, ... by overriding the
//! `rust_llm::Agent` methods; every one has a default.
//!
//! Plain chat: `{{class_name}}.chat()?.ask("...")`. Persisted chat (RubyLLM's `chat_model Chat`):
//! `let mut chat = {{class_name}}.apply(record.to_llm(&db).await?)?;` then
//! `record.ask(&db, &mut chat, "...")`.

use rust_llm::Agent;

pub struct {{class_name}};

impl Agent for {{class_name}} {
    /// `src/prompts/{{file_name}}/instructions.txt`. An empty prompt file means no instructions,
    /// like RubyLLM's `blank_instruction?`.
    fn instructions(&self) -> Option<String> {
        let text = include_str!("../prompts/{{file_name}}/instructions.txt");
        (!text.trim().is_empty()).then(|| text.to_string())
    }
}
