//! `Chat`, the model that `acts_as_chat` (RubyLLM's `chat_model.rb.tt`). Generated by
//! `rust-llm generate install`. The table and persistence come from `rust_llm_loco`:
//! `ChatRecord::create(&db, model, provider)`, then `record.ask(&db, &mut chat, "...")`.

pub use rust_llm_loco::entities::chats::{ActiveModel, Column, Entity, Model};
pub use rust_llm_loco::ChatRecord;

use rust_llm_loco::entities::{messages, rust_llm_models, rust_llm_tool_calls, rust_llm_usages};
use rust_llm_loco::{CHAT_TYPE, MESSAGE_TYPE};
use sea_orm::sea_query::{Expr, ExprTrait};
use sea_orm::{
    ColumnTrait, DatabaseConnection, DbErr, EntityTrait, QueryFilter, QueryOrder, QuerySelect,
    TransactionTrait,
};
use serde_json::{json, Value};

/// `chat.model.label`: `"Anthropic - Claude Haiku 4.5"`.
#[must_use]
pub fn model_label(model: &rust_llm_models::Model) -> String {
    format!(
        "{} - {}",
        rust_llm::providers::display_name(&model.provider),
        model.name
    )
}

/// `Chat.order(created_at: :desc)` as page props, each with its model and message count.
///
/// # Errors
/// Database errors.
pub async fn list(db: &DatabaseConnection) -> Result<Vec<Value>, DbErr> {
    let chats = Entity::find()
        .order_by_desc(Column::CreatedAt)
        .order_by_desc(Column::Id)
        .all(db)
        .await?;
    let model_ids: Vec<i32> = chats.iter().map(|c| c.rust_llm_model_id).collect();
    let models = rust_llm_models::Entity::find()
        .filter(rust_llm_models::Column::Id.is_in(model_ids))
        .all(db)
        .await?;
    let counts: Vec<(i32, i64)> = messages::Entity::find()
        .select_only()
        .column(messages::Column::ChatId)
        .column_as(Expr::col(messages::Column::Id).count(), "count")
        .group_by(messages::Column::ChatId)
        .into_tuple()
        .all(db)
        .await?;
    Ok(chats
        .iter()
        .map(|chat| {
            let model = models.iter().find(|m| m.id == chat.rust_llm_model_id);
            let count = counts
                .iter()
                .find(|(id, _)| *id == chat.id)
                .map_or(0, |(_, n)| *n);
            json!({
                "id": chat.id,
                "model_label": model.map(model_label),
                "message_count": count,
                "created_at": chat.created_at.to_rfc3339(),
            })
        })
        .collect())
}

/// One chat as page props, `None` when it does not exist.
///
/// # Errors
/// Database errors.
pub async fn find_props(db: &DatabaseConnection, id: i32) -> Result<Option<Value>, DbErr> {
    let Some(chat) = Entity::find_by_id(id).one(db).await? else {
        return Ok(None);
    };
    let model = rust_llm_models::Entity::find_by_id(chat.rust_llm_model_id)
        .one(db)
        .await?;
    Ok(Some(json!({
        "id": chat.id,
        "model_label": model.as_ref().map(model_label),
        "created_at": chat.created_at.to_rfc3339(),
    })))
}

/// `chat.destroy!` with `acts_as_chat`'s `dependent: :destroy`: the chat's messages, their tool
/// calls, and its usage rows go with it.
///
/// # Errors
/// Database errors; nothing is deleted unless everything is.
pub async fn destroy(db: &DatabaseConnection, id: i32) -> Result<(), DbErr> {
    let txn = db.begin().await?;
    let message_ids: Vec<i64> = messages::Entity::find()
        .filter(messages::Column::ChatId.eq(id))
        .all(&txn)
        .await?
        .iter()
        .map(|m| i64::from(m.id))
        .collect();
    rust_llm_tool_calls::Entity::delete_many()
        .filter(rust_llm_tool_calls::Column::MessageType.eq(MESSAGE_TYPE))
        .filter(rust_llm_tool_calls::Column::MessageId.is_in(message_ids))
        .exec(&txn)
        .await?;
    rust_llm_usages::Entity::delete_many()
        .filter(rust_llm_usages::Column::ChatType.eq(CHAT_TYPE))
        .filter(rust_llm_usages::Column::ChatId.eq(i64::from(id)))
        .exec(&txn)
        .await?;
    messages::Entity::delete_many()
        .filter(messages::Column::ChatId.eq(id))
        .exec(&txn)
        .await?;
    Entity::delete_by_id(id).exec(&txn).await?;
    txn.commit().await
}
