//! `Message`, the model that `acts_as_message` (RubyLLM's `message_model.rb.tt`). Generated by
//! `rust-llm generate install`. Rows are written by `ChatRecord::ask`/`complete` in
//! `rust_llm_loco`, one per message as it is produced.

pub use rust_llm_loco::entities::messages::{ActiveModel, Column, Entity, Model};

use rust_llm_loco::entities::rust_llm_tool_calls;
use rust_llm_loco::MESSAGE_TYPE;
use sea_orm::{
    ActiveModelTrait, ActiveValue::Set, ColumnTrait, DatabaseConnection, DbErr, EntityTrait,
    QueryFilter, QueryOrder,
};
use serde_json::{json, Value};

/// `chat.ask_later(content)`: the user's message, stored before the model is called, so a
/// worker can `complete` the chat from its rows.
///
/// # Errors
/// Database errors.
pub async fn create_user(
    db: &DatabaseConnection,
    chat_id: i32,
    content: &str,
) -> Result<Model, DbErr> {
    let now: sea_orm::prelude::DateTimeWithTimeZone = chrono::Utc::now().into();
    ActiveModel {
        chat_id: Set(chat_id),
        role: Set("user".to_string()),
        content: Set(Some(content.to_string())),
        cache_until_here: Set(false),
        created_at: Set(now),
        updated_at: Set(now),
        ..Default::default()
    }
    .insert(db)
    .await
}

/// A chat's messages as page props, oldest first.
pub struct Transcript {
    /// Each message with its `tool_calls`, the `tool_name` of the call a tool result answers,
    /// and `tool_error_message`.
    pub messages: Vec<Value>,
    /// `!chat.complete?`: the last message still waits for the model (a user message, a tool
    /// result, or an assistant tool call whose results are coming).
    pub awaiting_response: bool,
}

/// `chat.messages.includes(:tool_calls)` as page props.
///
/// # Errors
/// Database errors.
pub async fn transcript(db: &DatabaseConnection, chat_id: i32) -> Result<Transcript, DbErr> {
    let rows = Entity::find()
        .filter(Column::ChatId.eq(chat_id))
        .order_by_asc(Column::Id)
        .all(db)
        .await?;
    let ids: Vec<i64> = rows.iter().map(|m| i64::from(m.id)).collect();
    let calls = rust_llm_tool_calls::Entity::find()
        .filter(rust_llm_tool_calls::Column::MessageType.eq(MESSAGE_TYPE))
        .filter(rust_llm_tool_calls::Column::MessageId.is_in(ids))
        .order_by_asc(rust_llm_tool_calls::Column::Id)
        .all(db)
        .await?;
    let messages = rows
        .iter()
        .map(|m| {
            let id = i64::from(m.id);
            let tool_calls: Vec<Value> = calls
                .iter()
                .filter(|c| c.message_id == id)
                .map(|c| {
                    json!({
                        "id": c.id,
                        "tool_call_id": c.tool_call_id,
                        "name": c.name,
                        "arguments": c.arguments.clone().unwrap_or_else(|| json!({})),
                    })
                })
                .collect();
            let parent = calls.iter().find(|c| {
                c.result_id == Some(id) && c.result_type.as_deref() == Some(MESSAGE_TYPE)
            });
            json!({
                "id": m.id,
                "role": m.role,
                "content": m.content,
                "created_at": m.created_at.to_rfc3339(),
                "tool_calls": tool_calls,
                "tool_name": parent.map(|c| c.name.clone()),
                "tool_error_message": (m.role == "tool")
                    .then(|| tool_error_message(m.content.as_deref()))
                    .flatten(),
            })
        })
        .collect();
    let awaiting_response = rows
        .iter()
        .rev()
        .find(|m| m.role != "system")
        .is_some_and(|last| match last.role.as_str() {
            "user" | "tool" => true,
            _ => calls.iter().any(|c| c.message_id == i64::from(last.id)),
        });
    Ok(Transcript {
        messages,
        awaiting_response,
    })
}

/// `message.tool_error_message`: the `error` of a tool result shaped `{"error": ...}`.
#[must_use]
pub fn tool_error_message(content: Option<&str>) -> Option<String> {
    let payload: Value = serde_json::from_str(content?).ok()?;
    match payload.get("error")? {
        Value::Null => None,
        Value::String(message) => Some(message.clone()),
        other => Some(other.to_string()),
    }
}
