//! A local stand-in for Anthropic's streaming Messages API, for the chat request tests
//! (generated by `rust-llm generate chat_ui` / `public_chat`). Every `POST /v1/messages` answers
//! `You said: <the last user message>` as Server-Sent Events, a few words per event with a short
//! pause between them, the way a real reply arrives. [`use_stub`] points RustLLM at it.

use std::{sync::Mutex, time::Duration};

use axum::{body::Body, http::header, response::Response, routing::post, Json, Router};
use futures_util::stream;
use serde_json::{json, Value};

/// The model the tests chat with (any id the registry knows; the stub ignores it).
pub const MODEL: &str = "claude-haiku-4-5";
/// The pause between two streamed events.
pub const EVENT_GAP: Duration = Duration::from_millis(60);

/// The body of the last request the stub answered.
static LAST_REQUEST: Mutex<Option<Value>> = Mutex::new(None);

/// The last Messages API request the app sent, if any.
#[must_use]
pub fn last_request() -> Option<Value> {
    LAST_REQUEST.lock().unwrap().clone()
}

/// Starts the stub and points RustLLM's Anthropic provider at it. Returns its base URL.
pub async fn use_stub() -> String {
    let app = Router::new().route("/v1/messages", post(messages));
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let base = format!("http://{}", listener.local_addr().unwrap());
    tokio::spawn(async move { axum::serve(listener, app).await.unwrap() });
    let url = base.clone();
    rust_llm::configure(move |config| {
        config.set("anthropic_api_base", url);
        config.set("anthropic_api_key", "test");
        config.max_retries = 0;
    });
    base
}

/// The text of the last user message in a Messages API request.
fn last_user_text(request: &Value) -> String {
    let Some(message) = request["messages"]
        .as_array()
        .and_then(|m| m.iter().rev().find(|m| m["role"] == "user"))
    else {
        return String::new();
    };
    match &message["content"] {
        Value::String(text) => text.clone(),
        Value::Array(blocks) => blocks
            .iter()
            .filter_map(|b| b["text"].as_str())
            .collect::<Vec<_>>()
            .join(""),
        _ => String::new(),
    }
}

/// What the stub replies to `request`.
#[must_use]
pub fn reply_to(request: &Value) -> String {
    format!("You said: {}", last_user_text(request))
}

fn event(name: &str, data: &Value) -> String {
    format!("event: {name}\ndata: {data}\n\n")
}

async fn messages(Json(request): Json<Value>) -> Response {
    let reply = reply_to(&request);
    *LAST_REQUEST.lock().unwrap() = Some(request);
    let words: Vec<String> = reply.split_inclusive(' ').map(str::to_owned).collect();
    let mut events = vec![
        event(
            "message_start",
            &json!({ "type": "message_start", "message": {
                "id": "msg_stub", "type": "message", "role": "assistant", "model": "claude-haiku-4-5-20251001",
                "content": [], "stop_reason": null,
                "usage": { "input_tokens": 10, "output_tokens": 1 } } }),
        ),
        event(
            "content_block_start",
            &json!({ "type": "content_block_start", "index": 0, "content_block": { "type": "text", "text": "" } }),
        ),
    ];
    events.extend(words.iter().map(|word| {
        event(
            "content_block_delta",
            &json!({ "type": "content_block_delta", "index": 0, "delta": { "type": "text_delta", "text": word } }),
        )
    }));
    events.push(event(
        "content_block_stop",
        &json!({ "type": "content_block_stop", "index": 0 }),
    ));
    events.push(event(
        "message_delta",
        &json!({ "type": "message_delta", "delta": { "stop_reason": "end_turn" }, "usage": { "output_tokens": words.len() } }),
    ));
    events.push(event("message_stop", &json!({ "type": "message_stop" })));
    let body = stream::unfold(events.into_iter(), |mut events| async move {
        let next = events.next()?;
        tokio::time::sleep(EVENT_GAP).await;
        Some((Ok::<_, std::convert::Infallible>(next), events))
    });
    Response::builder()
        .header(header::CONTENT_TYPE, "text/event-stream")
        .body(Body::from_stream(body))
        .unwrap()
}
