//! `{{class_name}}`, a RustLLM tool (RubyLLM's `tool.rb.tt`). Generated by
//! `rust-llm generate tool`. The model calls it as `{{tool_name}}`; the chat UI renders its calls
//! and results with `frontend/components/messages/tool_calls/{{tool_name}}.tsx` and
//! `tool_results/{{tool_name}}.tsx`.
//!
//! Declare arguments with `fn parameters(&self) -> Vec<rust_llm::Parameter>`, or a whole schema
//! with `fn parameters_schema` and `rust_llm::schema_for::<Args>()`.

use rust_llm::{Tool, ToolCall, ToolError, ToolResult};
use serde_json::{Map, Value};

pub struct {{class_name}};

#[async_trait::async_trait]
impl Tool for {{class_name}} {
    fn description(&self) -> String {
        "TODO: describe what this tool does".to_string()
    }

    async fn execute(
        &self,
        _arguments: Map<String, Value>,
        _tool_call: &ToolCall,
    ) -> Result<ToolResult, ToolError> {
        // TODO: return something to the LLM.
        // Anything you return here gets converted to a string.
        Ok("TODO: implement {{class_name}}".into())
    }
}
