//! `{{class_name}}`, a structured-output schema (RubyLLM's `schema.rb.tt`). Generated by
//! `rust-llm generate schema`. Add fields; doc comments become descriptions.
//!
//! `chat.with_schema_for::<{{class_name}}>().ask("...").await?.parsed()?`

#[derive(Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct {{class_name}} {}
