//! `ChatsController` (RubyLLM's chat_ui `chats_controller.rb.tt`) rendered through Inertia, for
//! signed-in users. Generated by `rust-llm generate chat_ui`. Chats are not scoped to a user,
//! as in RubyLLM's scaffold.

use loco_rs::prelude::*;
use serde::Deserialize;
use serde_json::json;

use crate::{
    auth::Authenticated,
    controllers::{models::available_chat_models, models::default_model_display_name},
    controllers::{render, NoPrecognition, Params},
    inertia::{redirect::Redirect, render::Inertia},
    models::{chats, messages},
    route_table,
    workers::chat_response::{ChatResponseArgs, ChatResponseWorker},
};

async fn index(
    _: Authenticated,
    State(ctx): State<AppContext>,
    inertia: Inertia,
) -> Result<Response> {
    let chats = chats::list(&ctx.db).await?;
    render(inertia, "chats/index", json!({ "chats": chats })).await
}

#[derive(Debug, Deserialize)]
pub struct NewParams {
    model: Option<String>,
    provider: Option<String>,
}

// `Params` reads the body, so it must be the last extractor.
async fn new(
    _: Authenticated,
    inertia: Inertia,
    Params(params): Params<NewParams>,
) -> Result<Response> {
    // `params[:provider] ? [params[:provider], params[:model]].join(":") : params[:model]`
    let selected_model = match (params.provider, params.model) {
        (Some(provider), Some(model)) => Some(format!("{provider}:{model}")),
        (_, model) => model,
    };
    let props = json!({
        "chat_models": available_chat_models(),
        "selected_model": selected_model,
        "default_model_label": default_model_display_name(),
    });
    render(inertia, "chats/new", props).await
}

#[derive(Debug, Deserialize)]
pub struct CreateParams {
    #[serde(default)]
    model: String,
    #[serde(default)]
    prompt: String,
}

/// Creates the chat with the prompt as its first message, then answers it in the background.
async fn create(
    _: NoPrecognition,
    _: Authenticated,
    State(ctx): State<AppContext>,
    Params(params): Params<CreateParams>,
) -> Result<Response> {
    let back = || {
        let query = serde_urlencoded::to_string([("model", &params.model)]).unwrap_or_default();
        Redirect::to(format!("{}?{query}", route_table::NEW_CHAT))
    };
    if params.prompt.trim().is_empty() {
        return Ok(back()
            .errors(json!({ "prompt": ["can't be blank"] }))
            .into_response());
    }
    // "provider:model", or blank for the configured default model.
    let (provider, model) = match params.model.split_once(':') {
        Some((provider, model)) => (Some(provider).filter(|p| !p.is_empty()), model.to_string()),
        None if params.model.is_empty() => (None, rust_llm::config().default_model.clone()),
        None => (None, params.model.clone()),
    };
    let record = match chats::ChatRecord::create(&ctx.db, &model, provider).await {
        Ok(record) => record,
        Err(rust_llm_loco::Error::Llm(e)) => {
            return Ok(back()
                .errors(json!({ "model": [e.to_string()] }))
                .into_response());
        }
        Err(e) => return Err(Error::wrap(e)),
    };
    messages::create_user(&ctx.db, record.id(), &params.prompt).await?;
    ChatResponseWorker::perform_later(
        &ctx,
        ChatResponseArgs {
            chat_id: record.id(),
        },
    )
    .await?;
    Ok(Redirect::to(route_table::chat_path(record.id()))
        .notice("Chat was successfully created.")
        .into_response())
}

async fn show(
    _: Authenticated,
    State(ctx): State<AppContext>,
    Path(id): Path<i32>,
    inertia: Inertia,
) -> Result<Response> {
    let chat = chats::find_props(&ctx.db, id)
        .await?
        .ok_or(Error::NotFound)?;
    let transcript = messages::transcript(&ctx.db, id).await?;
    let props = json!({
        "chat": chat,
        "messages": transcript.messages,
        "awaiting_response": transcript.awaiting_response,
        "default_model_label": default_model_display_name(),
    });
    render(inertia, "chats/show", props).await
}

async fn destroy(
    _: NoPrecognition,
    _: Authenticated,
    State(ctx): State<AppContext>,
    Path(id): Path<i32>,
) -> Result<Response> {
    chats::Entity::find_by_id(id)
        .one(&ctx.db)
        .await?
        .ok_or(Error::NotFound)?;
    chats::destroy(&ctx.db, id).await?;
    Ok(Redirect::to(route_table::CHATS)
        .notice("Chat was successfully destroyed.")
        .into_response())
}

pub fn routes() -> Routes {
    Routes::new()
        .add(route_table::CHATS, get(index).post(create))
        .add(route_table::NEW_CHAT, get(new))
        .add(route_table::CHAT, get(show).delete(destroy))
}
