//! `MessagesController` (RubyLLM's chat_ui `messages_controller.rb.tt`) rendered through
//! Inertia. Generated by `rust-llm generate chat_ui`.

use loco_rs::prelude::*;
use serde::Deserialize;
use serde_json::json;

use crate::{
    auth::Authenticated,
    controllers::{NoPrecognition, Params},
    inertia::redirect::Redirect,
    models::{chats, messages},
    route_table,
    workers::chat_response::{ChatResponseArgs, ChatResponseWorker},
};

#[derive(Debug, Deserialize)]
pub struct MessageParams {
    #[serde(default)]
    content: String,
}

/// Stores the user's message (`ask_later`), then answers it in the background.
async fn create(
    _: NoPrecognition,
    _: Authenticated,
    State(ctx): State<AppContext>,
    Path(chat_id): Path<i32>,
    Params(params): Params<MessageParams>,
) -> Result<Response> {
    chats::Entity::find_by_id(chat_id)
        .one(&ctx.db)
        .await?
        .ok_or(Error::NotFound)?;
    if params.content.trim().is_empty() {
        return Ok(Redirect::to(route_table::chat_path(chat_id))
            .errors(json!({ "content": ["can't be blank"] }))
            .into_response());
    }
    messages::create_user(&ctx.db, chat_id, &params.content).await?;
    ChatResponseWorker::perform_later(&ctx, ChatResponseArgs { chat_id }).await?;
    Ok(Redirect::to(route_table::chat_path(chat_id)).into_response())
}

pub fn routes() -> Routes {
    Routes::new().add(route_table::CHAT_MESSAGES, post(create))
}
