//! `MessagesController` (RubyLLM's chat_ui `messages_controller.rb.tt`) rendered through
//! Inertia, for a chat of the current account. Generated by `rust-llm generate chat_ui`.

use loco_rs::prelude::*;
use serde::Deserialize;
use serde_json::json;

use crate::{
    auth::CurrentAccount,
    controllers::{NoPrecognition, Params},
    inertia::redirect::Redirect,
    models::{chats, messages},
    route_table,
    workers::chat_response::{ChatResponseArgs, ChatResponseWorker},
};

#[derive(Debug, Deserialize)]
pub struct MessageParams {
    #[serde(default)]
    content: String,
}

/// Stores the user's message (`ask_later`), then answers it in the background.
async fn create(
    _: NoPrecognition,
    current: CurrentAccount,
    State(ctx): State<AppContext>,
    Path((_, chat_id)): Path<(String, i32)>,
    Params(params): Params<MessageParams>,
) -> Result<Response> {
    let account_id = current.account.id;
    chats::find_in_account(&ctx.db, account_id, chat_id)
        .await?
        .ok_or(Error::NotFound)?;
    let chat_path = route_table::chat_path(&current.account.slug, chat_id);
    if params.content.trim().is_empty() {
        return Ok(Redirect::to(chat_path)
            .errors(json!({ "content": ["can't be blank"] }))
            .into_response());
    }
    messages::create_user(&ctx.db, chat_id, &params.content).await?;
    ChatResponseWorker::perform_later(
        &ctx,
        ChatResponseArgs {
            account_id,
            chat_id,
        },
    )
    .await?;
    Ok(Redirect::to(chat_path).into_response())
}

pub fn routes() -> Routes {
    Routes::new().add(route_table::CHAT_MESSAGES, post(create))
}
