//! `ModelsController` (RubyLLM's chat_ui `models_controller.rb.tt`) rendered through Inertia.
//! Generated by `rust-llm generate chat_ui`. Models come from RustLLM's registry; `refresh`
//! reloads it from the configured providers and models.dev (`RubyLLM.models.refresh`).

use loco_rs::prelude::*;
use serde::Deserialize;
use serde_json::{json, Value};

use crate::{
    auth::Authenticated,
    controllers::{render, Params},
    inertia::{redirect::Redirect, render::Inertia},
    route_table,
};

/// `available_chat_models`: every listed chat model, sorted by provider then name.
#[must_use]
pub fn available_chat_models() -> Vec<Value> {
    let registry = rust_llm::models();
    let mut models = registry.chat_models();
    models.sort_by(|a, b| (&a.provider, &a.name).cmp(&(&b.provider, &b.name)));
    models.into_iter().map(model_props).collect()
}

/// `default_model_display_name`.
#[must_use]
pub fn default_model_display_name() -> String {
    let default = rust_llm::config().default_model.clone();
    match rust_llm::models().find(&default, None) {
        Ok(model) => format!("Default: {}", model.label()),
        Err(_) => format!("Default: {default}"),
    }
}

fn model_props(model: &rust_llm::Model) -> Value {
    let prices = model.pricing.text_tokens();
    json!({
        "id": model.id,
        "name": model.name,
        "provider": model.provider,
        "provider_name": rust_llm::providers::display_name(&model.provider),
        "label": model.label(),
        "value": format!("{}:{}", model.provider, model.id),
        "context_window": model.context_window,
        "max_output_tokens": model.max_output_tokens,
        "capabilities": model.capabilities,
        "input_price": prices.input(),
        "output_price": prices.output(),
    })
}

async fn index(_: Authenticated, inertia: Inertia) -> Result<Response> {
    render(
        inertia,
        "models/index",
        json!({ "models": available_chat_models() }),
    )
    .await
}

#[derive(Debug, Deserialize)]
pub struct ShowParams {
    provider: Option<String>,
}

async fn show(
    _: Authenticated,
    Path(id): Path<String>,
    inertia: Inertia,
    Params(params): Params<ShowParams>,
) -> Result<Response> {
    let model = rust_llm::models()
        .find(&id, params.provider.as_deref())
        .map_err(|_| Error::NotFound)?;
    render(
        inertia,
        "models/show",
        json!({ "model": model_props(&model) }),
    )
    .await
}

/// `refresh`: reloads the registry from the configured providers and models.dev.
async fn refresh(_: Authenticated) -> Result<Response> {
    rust_llm::models::refresh(false).await.map_err(Error::wrap)?;
    Ok(Redirect::to(route_table::MODELS)
        .notice("Models refreshed successfully")
        .into_response())
}

pub fn routes() -> Routes {
    Routes::new()
        .add(route_table::MODELS, get(index))
        .add(route_table::MODELS_REFRESH, post(refresh))
        .add(route_table::MODEL, get(show))
}
